name: env_click2cwl
channels:
  - terradue
  - conda-forge
dependencies:
  - python=3.8
  - click
  - pyyaml
  - mamba
  - pylint
  - black
  - autopep8
  - yapf
  - flake8
  - mypy
  - bandit
  - pycodestyle
  - pydocstyle
  - nose2
  - cwltool
