name: Publish to PyPI

on:
  push:
    branches: [develop, main, master]
    
  release:
    types: [published]
  pull_request:
    branches: [develop, main, master]
    
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        pip install hatch
    - name: Build and test package
      run: |
        hatch build
        pip install '.[test]'
        python tests/test_cwl.py
        pytest
    - name: Publish package distributions to PyPI (main)
      if: github.ref == 'refs/heads/master'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/
    - name: Publish package distributions to PyPI (develop)
      if: github.ref != 'refs/heads/master' 
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
